services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    working_dir: /app
    command: ["pnpm", "--filter", "web", "dev"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_BASE_URL=http://api:3001
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    working_dir: /app
    command: ["pnpm", "--filter", "api", "dev"]
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    name: myportfoliosite
